name: instagram
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.5
  dio: ^5.3.4
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.4
  flutter_riverpod: ^2.4.5
  formz: ^0.6.1
  geolocator: ^10.1.0
  go_router: ^12.0.1
  graphql: ^5.1.3
  http: ^1.1.0
  image: ^4.1.3
  image_picker: ^1.0.4
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  just_audio: ^0.9.36
  marquee: ^2.2.3
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.1
  video_player: ^2.8.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/icon/icon.png"
  min_sdk_android: 21
  # flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"

  android_12:
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#000000"

  web: false
flutter:
  uses-material-design: true

  assets:
    - lib/.env
    - lib/assets/instagram_letters2.png
    - lib/assets/icon/splash.png
    - lib/assets/meta.png
    - lib/assets/instagram_color.png
    - lib/assets/avatar_default.png
    - lib/assets/media_icon/
